#!/usr/bin/env python3

import sys
import os
import subprocess

NOTES_PATH = '/home/fabian/notebook'
NOTES_COMMAND = '(cd {} && vim)'.format(NOTES_PATH)


def get_command(argv):
    args = argv[:]
    args.pop(0)
    return ' '.join(args)


def exec_cmd(cmd):
    subprocess.call([os.getenv('SHELL'), '-i', '-c', cmd])


def open_notes():
    exec_cmd(NOTES_COMMAND)


def run_cmd(command):
    exec_cmd('(cd {} && {})'.format(NOTES_PATH, command))


if __name__ == '__main__':
    if len(sys.argv) > 1:
        run_cmd(get_command(sys.argv))
    else:
        open_notes()
